version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - depguard
    - dupl
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - gosec
    - ineffassign
    - ireturn
    - makezero
    - mnd
    - nakedret
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - revive
    - tagalign
    - tagliatelle
    - thelper
    - tparallel
    - unparam
    - unused
    - varnamelen
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
